# -*- coding: utf-8 -*-
"""NER_ORG_PER.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kiYDJ05qN1R8RTjsdq_4IZ8FheUIEc3w
"""


import datasets
import numpy as np
from transformers import BertTokenizerFast
from transformers import DataCollatorForTokenClassification
from transformers import AutoModelForTokenClassification
try:
    conll2003 = datasets.load_dataset("eriktks/conll2003")
except Exception:
    conll2003 = datasets.load_dataset("lhoestq/conll2003")

print(conll2003)

conll2003.shape

conll2003['train'][0]

conll2003['train'].features['ner_tags']

conll2003['train'].description

tokenizer = BertTokenizerFast.from_pretrained('bert-base-cased')

example_text = conll2003['train'][0]
tokenized_input = tokenizer(example_text['tokens'], is_split_into_words=True)
tokens = tokenizer.convert_ids_to_tokens(tokenized_input['input_ids'])
word_ids = tokenized_input.word_ids()

word_ids

from datasets import ClassLabel, Sequence


labels = [
    "O",
    "B-PER",
    "I-PER",
    "B-ORG",
    "I-ORG",
    "B-LOC",
    "I-LOC",
    "B-MISC",
    "I-MISC",
]


new_features = conll2003["train"].features.copy()
new_features["ner_tags"] = Sequence(ClassLabel(names=labels))


conll2003 = conll2003.cast(new_features)

def tokenize_and_align_labels(example, label_all_tokens=True):
  tokenized_input = tokenizer(example['tokens'], truncation = True, is_split_into_words=True)
  labels = []

  for i, label in enumerate(example['ner_tags']):
    word_ids = tokenized_input.word_ids(batch_index=i)

    previouts_word_idx = None

    label_ids = []

    for word_idx in word_ids:
      if word_idx is None:
        label_ids.append(-100)
      elif word_idx != previouts_word_idx:
        label_ids.append(label[word_idx])
      else:
        label_ids.append(label[word_idx] if label_all_tokens else -100)
      previouts_word_idx = word_idx
    labels.append(label_ids)
  tokenized_input['labels'] = labels
  return tokenized_input



q = tokenize_and_align_labels(conll2003["train"][4:6])
print(q)

for token, label in zip(tokenizer.convert_ids_to_tokens(q['input_ids'][0]), q['labels'][0]):
  print(f"{token: <40} {label}")

tokenized_dataset = conll2003.map(tokenize_and_align_labels, batched = True)



model = AutoModelForTokenClassification.from_pretrained('bert-base-cased', num_labels = 9)

from transformers import TrainingArguments, Trainer

args = TrainingArguments(
    output_dir="bert-ner-conll2003",  # Папка для збереження точок чекпоінтів
    eval_strategy="epoch",  # Оцінка моделі наприкінці кожної епохи (замість evaluation_strategy)
    save_strategy="epoch",  # Збереження моделі наприкінці кожної епохи
    learning_rate=2e-5,  # Стандартний оптимальний learning rate для BERT
    per_device_train_batch_size=16,  # Розмір батчу для тренування
    per_device_eval_batch_size=16,  # Розмір батчу для перевірки
    num_train_epochs=3,  # 3 епохи дадуть точність ~95%
    weight_decay=0.01,  # Регуляризація для запобігання перенавчанню
    load_best_model_at_end=True,  # В кінці збереже найкращу версію моделі
    metric_for_best_model="f1",  # Визначати найкращу модель за F1-score
)

data_collator = DataCollatorForTokenClassification(tokenizer)


import evaluate

metric = evaluate.load("seqeval")
example = conll2003['train'][0]

label_list = conll2003["train"].features["ner_tags"].feature.names
print(label_list)

labels = [label_list[i] for i in example['ner_tags']]
labels

metric.compute(predictions=[labels], references=[labels])

def compute_metrics(eval_preds):
    pred_logits, labels = eval_preds
    pred_logits = np.argmax(pred_logits, axis=2)

    predictions = [
        [
            label_list[p]
            for (p, l) in zip(prediction, label)
            if l != -100
        ]
        for prediction, label in zip(pred_logits, labels)
    ]

    true_labels = [
        [
            label_list[l]
            for (p, l) in zip(prediction, label)
            if l != -100
        ]
        for prediction, label in zip(pred_logits, labels)
    ]

    results = metric.compute(
        predictions=predictions, references=true_labels
    )

    return {
        "precision": results["overall_precision"],
        "recall": results["overall_recall"],
        "f1": results["overall_f1"],
        "accuracy": results["overall_accuracy"],
    }

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["validation"],
    data_collator=data_collator,
    processing_class=tokenizer,
    compute_metrics=compute_metrics,
)

trainer.train()

model.save_pretrained("ner_model")
tokenizer.save_pretrained("tokenizer")



id2label = {
    str(i) : label for i, label in enumerate(label_list)
}

label2id = {
    label: str(i) for i, label in enumerate(label_list)
}

import json

config = json.load(open('ner_model/config.json'))

import json

config["id2label"] = id2label
config["label2id"] = label2id

with open("ner_model/config.json", "w") as f:
    json.dump(config, f)

model_fine_tuned = AutoModelForTokenClassification.from_pretrained(
    "ner_model"
)

from transformers import pipeline

nlp = pipeline("ner", model=model_fine_tuned, tokenizer=tokenizer)
example = [
    "Elon Musk announced that Tesla will open a new gigafactory in Berlin.",
    "Barack Obama visited London during his presidency.",
    "Tim Cook and Jeff Bezos met at the United Nations headquarters in New York.",
    "The FIFA World Cup in Qatar featured team France playing against Argentina.",
    "Google and Apple are American technology giants working on AI.",
    "Yesterday I bought three books and drank coffee at home."
]

ner_results = nlp(example)
print(ner_results)

test_results = trainer.evaluate(eval_dataset=tokenized_dataset["test"])
print("Test Set Metrics:", test_results)


